### ISSUE TITLE
[MSOURCES-44] If project doesn't contain sources (contains only test sources) source:jar will fail

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-source-plugin#130]
**[syvalta](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=syvalta)** opened **[MSOURCES-44](https://issues.apache.org/jira/browse/MSOURCES-44?redirect=false)** and commented

We are running all of our CI builds with the release profile so that javadocs and sources are generated. However, one module in a multi-module build contains only test sources. After updating from 2.0.4 to 2.1 the build will fail. The same error occurs when source:jar is run manually. Below is the stack trace from jar:source. It might be intentional that the build will fail in case source:jar is run from command line, but when using release profile the failure is quite problematic.

[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error creating source archive: You must set at least one file.

[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error creating source archive: You must set at least one file.
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:703)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:553)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:523)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:371)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:332)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:181)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:356)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:137)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:356)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error creating source archive: You must set at least one file.
at org.apache.maven.plugin.source.AbstractSourceJarMojo.packageSources(AbstractSourceJarMojo.java:285)
at org.apache.maven.plugin.source.AbstractSourceJarMojo.packageSources(AbstractSourceJarMojo.java:232)
at org.apache.maven.plugin.source.AbstractSourceJarMojo.execute(AbstractSourceJarMojo.java:201)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:483)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:678)
... 16 more
Caused by: org.codehaus.plexus.archiver.ArchiverException: You must set at least one file.
at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.createArchiveMain(AbstractZipArchiver.java:260)
at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.execute(AbstractZipArchiver.java:242)
at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:673)
at org.apache.maven.archiver.MavenArchiver.createArchive(MavenArchiver.java:543)
at org.apache.maven.plugin.source.AbstractSourceJarMojo.packageSources(AbstractSourceJarMojo.java:277)
... 20 more

---

**Affects:** 2.1

**Attachments:**
- [failOnEmpty.patch](https://issues.apache.org/jira/secure/attachment/12719579/failOnEmpty.patch) (_1.50 kB_)
- [MSOURCES-44.patch](https://issues.apache.org/jira/secure/attachment/12719577/MSOURCES-44.patch) (_1017 bytes_)
- [MSOURCES-44.patch](https://issues.apache.org/jira/secure/attachment/12719576/MSOURCES-44.patch) (_720 bytes_)

25 votes, 21 watchers

**Comment by jira-importer** [comment]
**[Ben Tatham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentatham)** commented

We have the same issue, with some test-less projects (like parent pom projects, that are themselves a child pom of our overall company pom that says to create source and test-source jars for all projects, using no-fork goals).

**Comment by jira-importer** [comment]
**[Ben Tatham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentatham)** commented

Here is a simple patch to provide a "failOnEmpty" parameter that can be set to false to skip ArchiverException.  I could not see a simple way to check if no files are specified before calling the archiver, or to check that this is the reason for the ArchiverException.  But it works for me.

Note: Must set attach=false to avoid trying to install/deploy a file that does not exist.

**Comment by jira-importer** [comment]
**[Markku Saarela](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ivalo)** commented

Source plugin must obey  maven archiver \<addMavenDescriptor/> which defaults to true, so source plugin must insert by default these two files and then this source jar file is not empty. See jar plugin implementation.

**Comment by jira-importer** [comment]
**[Thomas Swindells](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tswindells)** commented

This issue is also affecting me. In my case the project is a submodule that uses jaxb to convert schemas into generated code which is then compiled into a jar.

**Comment by jira-importer** [comment]
**[James William Dumay](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jameswdumay)** commented

Id suggest the following patch that simply checks that the archiver has files before it attempts to create it. Having a configuration option for something that is clearly a regression is probably not a good idea.

Maintainers can bug me for a functional test if they want one :)

**Comment by jira-importer** [comment]
**[James William Dumay](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jameswdumay)** commented

Updated patch so that it does not attach the artifact if it was not created.
