### ISSUE TITLE
[MSOURCES-62] An API incompatibility was encountered.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-source-plugin#152]
**[Christian Schulte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=schulte77)** opened **[MSOURCES-62](https://issues.apache.org/jira/browse/MSOURCES-62?redirect=false)** and commented

The plugin fails when using custom 'manifestEntries' throwing the following exception:

```
[...]
Caused by: java.lang.NoSuchMethodError: org.codehaus.plexus.archiver.jar.Manifest.getMainSection()Lorg/codehaus/plexus/archiver/jar/Manifest$Section;
        at org.apache.maven.archiver.MavenArchiver.getManifest(MavenArchiver.java:102)
        at org.apache.maven.archiver.MavenArchiver.createArchive(MavenArchiver.java:513)
        at org.apache.maven.plugin.source.AbstractSourceJarMojo.packageSources(AbstractSourceJarMojo.java:288)
        at org.apache.maven.plugin.source.AbstractSourceJarMojo.packageSources(AbstractSourceJarMojo.java:240)
        at org.apache.maven.plugin.source.AbstractSourceJarMojo.execute(AbstractSourceJarMojo.java:209)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        ... 20 more
```

---

**Affects:** 2.2

**Attachments:**
- [MSOURCES-62.zip](https://issues.apache.org/jira/secure/attachment/12719583/MSOURCES-62.zip) (_1.52 kB_)

1 votes, 6 watchers

**Comment by jira-importer** [comment]
**[Christian Schulte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=schulte77)** commented

Example project demonstrating the issue.

**Comment by jira-importer** [comment]
**[Christian Schulte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=schulte77)** commented

```
Script started on Sat Aug 18 00:21:29 2012
$ mvn -e package

[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building 62 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ 62 ---
[debug] execute contextualize
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ 62 ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ 62 ---
[debug] execute contextualize
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /tmp/MSOURCES-62/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ 62 ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.10:test (default-test) @ 62 ---
[INFO] No tests to run.
[INFO] Surefire report directory: /tmp/MSOURCES-62/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.3.2:jar (default-jar) @ 62 ---
[INFO] Building jar: /tmp/MSOURCES-62/target/62-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-source-plugin:2.2:jar-no-fork (default) @ 62 ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.051s
[INFO] Finished at: Sat Aug 18 00:21:43 CEST 2012
[INFO] Final Memory: 6M/15M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-source-plugin:2.2:jar-no-fork (default) on project 62: Execution default of goal org.apache.maven.plugins:maven-source-plugin:2.2:jar-no-fork failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-source-plugin:2.2:jar-no-fork: java.lang.NoSuchMethodError: org.codehaus.plexus.archiver.jar.Manifest.getMainSection()Lorg/codehaus/plexus/archiver/jar/Manifest$Section;
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.maven.plugins:maven-source-plugin:2.2
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/schulte/.m2/central/org/apache/maven/plugins/maven-source-plugin/2.2/maven-source-plugin-2.2.jar
[ERROR] urls[1] = file:/home/schulte/.m2/central/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] urls[2] = file:/home/schulte/.m2/central/org/apache/maven/maven-archiver/2.4.1/maven-archiver-2.4.1.jar
[ERROR] urls[3] = file:/home/schulte/.m2/central/org/codehaus/plexus/plexus-interpolation/1.13/plexus-interpolation-1.13.jar
[ERROR] urls[4] = file:/home/schulte/.m2/central/org/codehaus/plexus/plexus-archiver/2.1.2/plexus-archiver-2.1.2.jar
[ERROR] urls[5] = file:/home/schulte/.m2/central/org/codehaus/plexus/plexus-io/2.0.4/plexus-io-2.0.4.jar
[ERROR] urls[6] = file:/home/schulte/.m2/central/org/codehaus/plexus/plexus-utils/3.0.1/plexus-utils-3.0.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-source-plugin:2.2:jar-no-fork (default) on project 62: Execution default of goal org.apache.maven.plugins:maven-source-plugin:2.2:jar-no-fork failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-source-plugin:2.2:jar-no-fork: java.lang.NoSuchMethodError: org.codehaus.plexus.archiver.jar.Manifest.getMainSection()Lorg/codehaus/plexus/archiver/jar/Manifest$Section;
-----------------------------------------------------
realm =    plugin>org.apache.maven.plugins:maven-source-plugin:2.2
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/home/schulte/.m2/central/org/apache/maven/plugins/maven-source-plugin/2.2/maven-source-plugin-2.2.jar
urls[1] = file:/home/schulte/.m2/central/junit/junit/3.8.1/junit-3.8.1.jar
urls[2] = file:/home/schulte/.m2/central/org/apache/maven/maven-archiver/2.4.1/maven-archiver-2.4.1.jar
urls[3] = file:/home/schulte/.m2/central/org/codehaus/plexus/plexus-interpolation/1.13/plexus-interpolation-1.13.jar
urls[4] = file:/home/schulte/.m2/central/org/codehaus/plexus/plexus-archiver/2.1.2/plexus-archiver-2.1.2.jar
urls[5] = file:/home/schulte/.m2/central/org/codehaus/plexus/plexus-io/2.0.4/plexus-io-2.0.4.jar
urls[6] = file:/home/schulte/.m2/central/org/codehaus/plexus/plexus-utils/3.0.1/plexus-utils-3.0.1.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.apache.maven.plugins:maven-source-plugin:2.2:jar-no-fork failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-source-plugin:2.2:jar-no-fork: java.lang.NoSuchMethodError: org.codehaus.plexus.archiver.jar.Manifest.getMainSection()Lorg/codehaus/plexus/archiver/jar/Manifest$Section;
-----------------------------------------------------
realm =    plugin>org.apache.maven.plugins:maven-source-plugin:2.2
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/home/schulte/.m2/central/org/apache/maven/plugins/maven-source-plugin/2.2/maven-source-plugin-2.2.jar
urls[1] = file:/home/schulte/.m2/central/junit/junit/3.8.1/junit-3.8.1.jar
urls[2] = file:/home/schulte/.m2/central/org/apache/maven/maven-archiver/2.4.1/maven-archiver-2.4.1.jar
urls[3] = file:/home/schulte/.m2/central/org/codehaus/plexus/plexus-interpolation/1.13/plexus-interpolation-1.13.jar
urls[4] = file:/home/schulte/.m2/central/org/codehaus/plexus/plexus-archiver/2.1.2/plexus-archiver-2.1.2.jar
urls[5] = file:/home/schulte/.m2/central/org/codehaus/plexus/plexus-io/2.0.4/plexus-io-2.0.4.jar
urls[6] = file:/home/schulte/.m2/central/org/codehaus/plexus/plexus-utils/3.0.1/plexus-utils-3.0.1.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:139)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: org.apache.maven.plugin.PluginContainerException: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-source-plugin:2.2:jar-no-fork: java.lang.NoSuchMethodError: org.codehaus.plexus.archiver.jar.Manifest.getMainSection()Lorg/codehaus/plexus/archiver/jar/Manifest$Section;
-----------------------------------------------------
realm =    plugin>org.apache.maven.plugins:maven-source-plugin:2.2
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/home/schulte/.m2/central/org/apache/maven/plugins/maven-source-plugin/2.2/maven-source-plugin-2.2.jar
urls[1] = file:/home/schulte/.m2/central/junit/junit/3.8.1/junit-3.8.1.jar
urls[2] = file:/home/schulte/.m2/central/org/apache/maven/maven-archiver/2.4.1/maven-archiver-2.4.1.jar
urls[3] = file:/home/schulte/.m2/central/org/codehaus/plexus/plexus-interpolation/1.13/plexus-interpolation-1.13.jar
urls[4] = file:/home/schulte/.m2/central/org/codehaus/plexus/plexus-archiver/2.1.2/plexus-archiver-2.1.2.jar
urls[5] = file:/home/schulte/.m2/central/org/codehaus/plexus/plexus-io/2.0.4/plexus-io-2.0.4.jar
urls[6] = file:/home/schulte/.m2/central/org/codehaus/plexus/plexus-utils/3.0.1/plexus-utils-3.0.1.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        ... 20 more
Caused by: java.lang.NoSuchMethodError: org.codehaus.plexus.archiver.jar.Manifest.getMainSection()Lorg/codehaus/plexus/archiver/jar/Manifest$Section;
        at org.apache.maven.archiver.MavenArchiver.getManifest(MavenArchiver.java:102)
        at org.apache.maven.archiver.MavenArchiver.createArchive(MavenArchiver.java:513)
        at org.apache.maven.plugin.source.AbstractSourceJarMojo.packageSources(AbstractSourceJarMojo.java:288)
        at org.apache.maven.plugin.source.AbstractSourceJarMojo.packageSources(AbstractSourceJarMojo.java:240)
        at org.apache.maven.plugin.source.AbstractSourceJarMojo.execute(AbstractSourceJarMojo.java:209)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        ... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
$ ^D


Script done on Sat Aug 18 00:21:45 2012
```

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

due to https://github.com/sonatype/plexus-archiver/commit/838ab2e61ab6540631abe8a792292ea672e97a85#src/main/java/org/codehaus/plexus/archiver/jar/Manifest.java

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

fixed.
Thanks for the it test!

**Comment by jira-importer** [comment]
**[lefebvre](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jflefebvre)** commented

Any idea when the 2.3 version will be released ?
