### ISSUE TITLE
[MSOURCES-104] Version 3.0.1 results in build failures

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-source-plugin#176]
**[Corey Schooler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=corey.schooler)** opened **[MSOURCES-104](https://issues.apache.org/jira/browse/MSOURCES-104?redirect=false)** and commented

When updating the pom to support plexus-archiver 3.2, a transitive dependency on commons-io 2.5 was introduced.  Starting [after commit 1742763](http://svn.apache.org/viewvc/maven/plugins/trunk/maven-source-plugin/pom.xml?view=markup&pathrev=1742763) when building maven-source-plugin, maven started logging the below `WARNING`.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce (enforce-bytecode-version) on project maven-source-plugin: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce (enforce-bytecode-version) on project maven-source-plugin: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
        at org.apache.maven.plugins.enforcer.EnforceMojo.execute(EnforceMojo.java:209)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
```

It seems that commons-io 2.5 was built with a JDK not supported by the enforcer plugin's restrictions.  This results in the following error messages when I build local projects:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-source-plugin:3.0.1:jar-no-fork (default) on project user-roster-config: Execution default of goal org.apache.maven.plugins:maven-source-plugin:3.0.1:jar-no-fork failed: A required class was missing while executing org.apache.maven.plugins:maven-source-plugin:3.0.1:jar-no-fork: org/apache/commons/io/output/DeferredFileOutputStream
```

---

**Affects:** 3.0.1

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

What do you mean by `updating the pom to support plexus-archiver 3.2` ? Maven Source Plugin contains plexus-archiver version 3.4? Furthermore which version of byte-code version are you checking against via Maven Enforcer Plugin ? You have read the announcement mail which contains an important hint about minimum JDK 6 and Maven 3+ ?
