### ISSUE TITLE
[MSOURCES-119] Archiving to jar is very slow

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-source-plugin#183]
**[Claes Nordmark](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nordmcla)** opened **[MSOURCES-119](https://issues.apache.org/jira/browse/MSOURCES-119?redirect=false)** and commented

Doing a stackdump while "maven-source-plugin:3.0.0:jar-no-fork (attach-sources)" shows thread spending a lot of time in UnixNativeDispatcher.getgrgid.

This was not visible in java 8 and source plugin version 2.4.

Our previous build time has been increased from 5min to 3h 30min.

Tested version Java 11 and 3.0.0 of maven-source-plugin

maven config:

```xml
 <plugin>
 <groupId>org.apache.maven.plugins</groupId>
 <artifactId>maven-source-plugin</artifactId>
 <version>3.0.0</version>
 <executions>
   <execution>
     <id>attach-sources</id>
     <goals>
       <goal>jar-no-fork</goal>
     </goals>
   </execution>
 </executions>
 </plugin>
```

```
java.lang.Thread.State: RUNNABLE}}
 at sun.nio.fs.UnixNativeDispatcher.getgrgid(java.base@11/Native Method)
 at sun.nio.fs.UnixUserPrincipals.fromGid(java.base@11/UnixUserPrincipals.java:129)
 at sun.nio.fs.UnixFileAttributes.group(java.base@11/UnixFileAttributes.java:208)
 - locked <0x00000006b0773fd8> (a sun.nio.fs.UnixFileAttributes)
 at sun.nio.fs.UnixFileAttributeViews$Posix.addRequestedPosixAttributes(java.base@11/UnixFileAttributeViews.java:214)
 at sun.nio.fs.UnixFileAttributeViews$Unix.readAttributes(java.base@11/UnixFileAttributeViews.java:362)
 at sun.nio.fs.AbstractFileSystemProvider.readAttributes(java.base@11/AbstractFileSystemProvider.java:94)
 at java.nio.file.Files.readAttributes(java.base@11/Files.java:1996)
 at org.codehaus.plexus.components.io.attributes.Java7FileAttributes.<init>(Java7FileAttributes.java:65)
 at org.codehaus.plexus.components.io.resources.PlexusIoFileResourceCollection.addResourcesJava7(PlexusIoFileResourceCollection.java:192)
 at org.codehaus.plexus.components.io.resources.PlexusIoFileResourceCollection.getResources(PlexusIoFileResourceCollection.java:287)
 at org.codehaus.plexus.archiver.AbstractArchiver$1.hasNext(AbstractArchiver.java:504)
 at org.apache.maven.plugins.source.AbstractSourceJarMojo.packageSources(AbstractSourceJarMojo.java:287)
```

---

**Affects:** 3.0.0

**Issue Links:**
- [MJAR-259](https://issues.apache.org/jira/browse/MJAR-259) Archiving to jar is very slow

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Have you checked with the most recent version of maven-jar-plugin? 3.1.0?

**Comment by jira-importer** [comment]
**[Claes Nordmark](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nordmcla)** commented

Yes, tested it now and its the same behavior :(

**Comment by jira-importer** [comment]
**[Claes Nordmark](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nordmcla)** commented

I've checked and java version seems to be irrelevant at least. Tried with both java 8 and java 11.

Different maven versions have been tested as well, 3.2.1 and 3.5.4.

I've raised another ticket on plexus archiver, which could be something to take as input:

https://github.com/codehaus-plexus/plexus-archiver/issues/105

maven is run like this: "mvn package -Dmaven.skip.test=true"

**Comment by jira-importer** [comment]
**[Claes Nordmark](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nordmcla)** commented

Ive made a test with https://github.com/ThomasJaspers/java-junit-sample project.
I just added this in the pom.xml:

```java
<build> 
<plugins> 
  <plugin> 
    <groupId>org.apache.maven.plugins</groupId> 
    <artifactId>maven-javadoc-plugin</artifactId> 
    <version>${maven.javadoc.plugin.version}</version> 
    <executions> 
      <execution> <id>attach-javadocs</id> 
        <goals> 
          <goal>jar</goal> 
        </goals> 
        <configuration>
          <failOnError>false</failOnError>
        </configuration> 
      </execution>
    </executions> 
  </plugin> 
  <plugin> 
    <groupId>org.apache.maven.plugins</groupId> 
    <artifactId>maven-source-plugin</artifactId>   
    <version>${maven.source.plugin.version}</version>
    <executions> 
      <execution> <id>attach-sources</id> 
        <goals> 
          <goal>jar</goal> 
        </goals> 
      </execution> 
    </executions> 
  </plugin> 
  <plugin>   
      <groupId>org.apache.maven.plugins</groupId> <artifactId>maven-jar-plugin</artifactId>     
      <version>${maven.jar.plugin.version}</version> <configuration> 
      <archive> 
        <index>true</index> 
          <manifest>              
            <addClasspath>true</addClasspath> 
          </manifest> 
        </archive> 
      </configuration> 
    </plugin> 
  </plugins> 
</build>
```

with new versions of maven plugins I get:

```java
<properties> <maven.compiler.source>1.8</maven.compiler.source> <maven.compiler.target>1.8</maven.compiler.target> <maven.source.plugin.version>3.0.0</maven.source.plugin.version> <maven.javadoc.plugin.version>3.0.1</maven.javadoc.plugin.version> <maven.jar.plugin.version>3.1.0</maven.jar.plugin.version> </properties>
```

[INFO] Building jar: /test-project/target/my-app-1.0-SNAPSHOT-sources.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.479 s
[INFO] Finished at: 2018-11-14T13:22:46+01:00
[INFO] Final Memory: 33M/597M
[INFO] ------------------------------------------------------------------------

and with old:

```java
<properties> <maven.compiler.source>1.8</maven.compiler.source> <maven.compiler.target>1.8</maven.compiler.target> <maven.source.plugin.version>2.4</maven.source.plugin.version> <maven.javadoc.plugin.version>2.10.1</maven.javadoc.plugin.version> <maven.jar.plugin.version>2.6</maven.jar.plugin.version> </properties>
```

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.710 s
[INFO] Finished at: 2018-11-14T13:25:28+01:00
[INFO] Final Memory: 40M/482M
[INFO] ------------------------------------------------------------------------

**Comment by jira-importer** [comment]
**[Claes Nordmark](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nordmcla)** commented

Also some more input using maven-profiler:

 Run package on 2018/11/14 13:55:19 with parameters: {maven.test.skip=true, profile=true, disableTimeSorting=true}
my-app (44.61 s)
Plugin execution Duration
org.apache.maven.plugins:maven-resources-plugin:2.6:resources {execution: default-resources} 889.8 ms
org.apache.maven.plugins:maven-compiler-plugin:3.1:compile {execution: default-compile} 1.402 s
org.apache.maven.plugins:maven-resources-plugin:2.6:testResources {execution: default-testResources} 2.019 ms
org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile {execution: default-testCompile} 1.383 ms
org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test {execution: default-test} 480.9 ms
org.apache.maven.plugins:maven-jar-plugin:**3.1.0**:jar {execution: default-jar} 6.388 s
org.apache.maven.plugins:maven-javadoc-plugin:**3.0.1**:jar {execution: attach-javadocs} 21.25 s
org.apache.maven.plugins:maven-source-plugin:**3.0.0**:jar {execution: attach-sources} 11.33 s

my-app (11.86 s)

Run package on 2018/11/14 13:56:33 with parameters: {maven.test.skip=true, profile=true, disableTimeSorting=true}
my-app (11.37 s)
Plugin execution Duration
org.apache.maven.plugins:maven-resources-plugin:2.6:resources {execution: default-resources} 801.5 ms
org.apache.maven.plugins:maven-compiler-plugin:3.1:compile {execution: default-compile} 2.328 s
org.apache.maven.plugins:maven-resources-plugin:2.6:testResources {execution: default-testResources} 3.180 ms
org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile {execution: default-testCompile} 1.603 ms
org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test {execution: default-test} 414.0 ms
org.apache.maven.plugins:maven-jar-plugin:**2.6**:jar {execution: default-jar} 1.892 s
org.apache.maven.plugins:maven-javadoc-plugin*:2.10.1*:jar {execution: attach-javadocs} 2.921 s
org.apache.maven.plugins:maven-source-plugin:**2.4**:jar {execution: attach-sources} 1.242 s

**Comment by jira-importer** [comment]
**[Claes Nordmark](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nordmcla)** commented

Narrowed down to https://github.com/codehaus-plexus/plexus-io/pull/17 :) made a push for a fix to plexus-io
