### ISSUE TITLE
[MSOURCES-16] Unable to find the mojo 'org.apache.maven.plugins:maven-source-plugin:2.0.3:aggregate'

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-source-plugin#92]
**[KlaasJan Elzinga](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=klaasjanelzinga)** opened **[MSOURCES-16](https://issues.apache.org/jira/browse/MSOURCES-16?redirect=false)** and commented

With a multi module project I receive the following exception:

[INFO] Error getting reports from the plugin 'org.apache.maven.plugins:maven-source-plugin': Unable to find the mojo 'org.apache.maven.plugins:maven-source-plugin:2.0.3:aggregate' in the plu
gin 'org.apache.maven.plugins:maven-source-plugin'
org/codehaus/plexus/archiver/ArchiverException
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error getting reports from the plugin 'org.apache.maven.plugins:maven-source-plugin': Unable to find the mojo 'org.apache.maven.plugin
s:maven-source-plugin:2.0.3:aggregate' in the plugin 'org.apache.maven.plugins:maven-source-plugin'
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.getReports(DefaultLifecycleExecutor.java:694)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.getReports(DefaultLifecycleExecutor.java:642)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:517)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:493)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:463)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:272)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.PluginManagerException: Unable to find the mojo 'org.apache.maven.plugins:maven-source-plugin:2.0.3:aggregate' in the plugin 'org.apache.maven.plugins:mave
n-source-plugin'
at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:571)
at org.apache.maven.plugin.DefaultPluginManager.getReport(DefaultPluginManager.java:495)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.getReports(DefaultLifecycleExecutor.java:683)
... 18 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Unable to lookup component 'org.apache.maven.plugin.Mojoorg.apache.maven.plugins:maven-source-plugin:2
.0.3:aggregate', it could not be created
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:335)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:440)
at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:562)
... 20 more
Caused by: org.codehaus.plexus.component.factory.ComponentInstantiationException: Could not instanciate component: role: 'null', implementation: 'org.apache.maven.plugin.source.AggregatorSou
rceJarMojo'
at org.codehaus.plexus.component.factory.java.JavaComponentFactory.makeException(JavaComponentFactory.java:77)
at org.codehaus.plexus.component.factory.java.JavaComponentFactory.newInstance(JavaComponentFactory.java:62)
at org.codehaus.plexus.DefaultPlexusContainer.createComponentInstance(DefaultPlexusContainer.java:1464)
at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:93)
at org.codehaus.plexus.component.manager.PerLookupComponentManager.getComponent(PerLookupComponentManager.java:48)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:331)
... 22 more
Caused by: java.lang.NoClassDefFoundError: org/codehaus/plexus/archiver/ArchiverException
at java.lang.Class.getDeclaredConstructors0(Native Method)
at java.lang.Class.privateGetDeclaredConstructors(Class.java:2357)
at java.lang.Class.getConstructor0(Class.java:2671)
at java.lang.Class.newInstance0(Class.java:321)
at java.lang.Class.newInstance(Class.java:303)
at org.codehaus.plexus.component.factory.java.JavaComponentFactory.newInstance(JavaComponentFactory.java:44)
... 26 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5 seconds
[INFO] Finished at: Thu Apr 26 09:49:55 CEST 2007
[INFO] Final Memory: 10M/19M
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.0.3

**Comment by jira-importer** [comment]
**[KlaasJan Elzinga](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=klaasjanelzinga)** commented

That resolved my problem. Thanx.

**Comment by jira-importer** [comment]
**[KlaasJan Elzinga](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=klaasjanelzinga)** commented

Issue caused by corrupt local repository. Resolved by commands in the comments.
